spring:
  application:
    name: everywhere
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret: ${JWT_SECRET_KEY}

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace