spring:
  application:
    name: everywhere
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/enjoytrip
    username: ssafy
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    resources:
      static-locations: file:${user.home}/uploads/

jwt:
  secret: c3NhZnlqd3RzZWNyZXRrZXkxMjM0c3NhZnlqd3RzZWNyZXRrZXkxMjM0

logging:
  level:
    root: info

server:
  address: 0.0.0.0
  port: 8080