spring:
  application:
    name: everywhere
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/enjoytrip
    username: ssafy
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    resources:
      static-locations: file:${user.home}/uploads/
  data:
    redis:
      repositories:
        enabled: true
      host: localhost
      port: 6379
      timeout: 5000 # 연결 타임아웃 (ms)
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1

jwt:
  secret: c3NhZnlqd3RzZWNyZXRrZXkxMjM0c3NhZnlqd3RzZWNyZXRrZXkxMjM0

logging:
  level:
    root: info

server:
  address: 0.0.0.0
  port: 8080
