spring:
  application:
    name: everywhere
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  datasource:
    url: jdbc:mysql://localhost:3306/enjoytrip
    username: ssafy
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    resources:
      static-locations: file:${user.home}/uploads/
  data:
    redis:
      repositories:
        enabled: true
      place:
        host: localhost
        port: 6379 # 79 : everywhere-redis
        index: idx:attraction
      user:
        host: localhost
        port: 6380 # 80 : everywhere-user-redis
        index: idx:route
      timeout: 5000 # 연결 타임아웃 (ms)
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1
  ai:
    openai:
      api-key: "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"
    ollama:
      chat:
        enabled: true # true
        options:
          model: qwen:0.5b # qwen2.5:7b # llama2
          temperature: 0.7
#        model: llama2
      base-url: "http://localhost:11434"
      embedding:
        enabled: false

jwt:
  secret: c3NhZnlqd3RzZWNyZXRrZXkxMjM0c3NhZnlqd3RzZWNyZXRrZXkxMjM0

logging:
  level:
    root: info

server:
  address: 0.0.0.0
  port: 8080

